- [cppreference.com](http://en.cppreference.com/w/) <!-- TAGS: cpp,documentation -->
- [Standard C++](https://isocpp.org/) <!-- TAGS: cpp -->
- [C++ in Competitive Programming: intro | Growing up](https://marcoarena.wordpress.com/2016/02/15/cpp-in-competitive-programming-intro/) <!-- TAGS: blog,cpp -->
- [Core C++ - lvalues and rvalues | Just Software Solutions - Custom Software Development](https://www.justsoftwaresolutions.co.uk/cplusplus/core-c++-lvalues-and-rvalues.html) <!-- TAGS: blog,cpp,lvalue,rvalue -->
- [Another polymorphism | Andrzej's C++ blog](https://akrzemi1.wordpress.com/2016/02/27/another-polymorphism/) <!-- TAGS: blog,cpp -->
- [Assembly Optimizations I: (Un)Packing Structures](https://haneefmubarak.com/2016/02/25/assembly-optimizations-i-un-packing-structures/) <!-- TAGS: asm,blog,cpp,x86 -->
- [C++ vtables - Part 3 - Virtual Inheritance | Shahar Mike's Web Spot](https://shaharmike.com/cpp/vtable-part3/) <!-- TAGS: blog,cpp -->
- [C++ in Competitive Programming: warmup | Growing up](https://marcoarena.wordpress.com/2016/04/14/cpp-in-competitive-programming-warmup/) <!-- TAGS: blog,cpp -->
- [itscompiling.eu](http://itscompiling.eu/2016/05/12/practical-cpp-value-categories/) <!-- TAGS: blog,cpp -->
- [Bartek's coding blog: Google benchmark library](http://www.bfilipek.com/2016/05/google-benchmark-library.html?m=1) <!-- TAGS: bartlomiej,bartlomiej filipek,benchmark,blog,c++,code,coding,cpp,filipek,gamedev,glsl,graphics,native,opengl,programming,shaders,software development,teaching,tutorials,vc++,visual c++,windows -->
- [C++ by Michael Tkach | ZEEF](https://cpp.zeef.com/michael.tkach) <!-- TAGS: blog,c++,cpp,development,documentation,language,programming -->
- [Outreachyfirstpatch - Linux Kernel Newbies](https://kernelnewbies.org/Outreachyfirstpatch) <!-- TAGS: kernel,linux -->
- [The Eudyptula Challenge](http://eudyptula-challenge.org/) <!-- TAGS: challenge,kernel,linux -->
- [How to create a <tt>sysfs</tt> file correctly - Linux Kernel Monkey Log](http://kroah.com/log/blog/2013/06/26/how-to-create-a-sysfs-file-correctly/) <!-- TAGS: kernel,linux -->
- [Linux Kernel Development Question : linux](https://www.reddit.com/r/linux/comments/36m9nf/linux_kernel_development_question/) <!-- TAGS: kernel,linux -->
- [You can be a kernel hacker! - Julia Evans](https://jvns.ca/blog/2014/09/18/you-can-be-a-kernel-hacker/) <!-- TAGS: kernel,linux -->
- [YouTube](https://www.youtube.com/watch?v=LLBrBBImJt4) <!-- TAGS: compartir,gratuito,kernel,linux,subida,teléfono con cámara,teléfono con vídeo,vídeo -->
- [Be a kernel hacker | Linux Voice](https://www.linuxvoice.com/be-a-kernel-hacker/) <!-- TAGS: kernel,linux -->
- [kernel hacking mini-howto](http://codemonkey.org.uk/projects/kernel/howto.php) <!-- TAGS: kernel,linux -->
- [4 paths to being a kernel hacker - Julia Evans](https://jvns.ca/blog/2014/01/04/4-paths-to-being-a-kernel-hacker/) <!-- TAGS: kernel,linux -->
- [Writing a File System in Linux Kernel](https://kukuruku.co/post/writing-a-file-system-in-linux-kernel/) <!-- TAGS: kernel,linux -->
- [Teaching the File System to Read](https://kukuruku.co/post/teaching-the-file-system-to-read/) <!-- TAGS: kernel,linux -->
- [Emacs configuration for Linux kernel development | Blog | Javier Martinez Canillas](https://blog.dowhile0.org/2011/07/04/emacs-configuration-for-linux-kernel-development/) <!-- TAGS: cscope,ctags,kernel,linux -->
- [A few spy tools for your operating system (other than strace!) - Julia Evans](https://jvns.ca/blog/2015/04/06/a-few-spy-tools-for-your-operating-system-other-than-strace/) <!-- TAGS: kernel,linux -->
- [Multitasking in the Linux Kernel. Interrupts and Tasklets](https://kukuruku.co/post/multitasking-in-the-linux-kernel-interrupts-and-tasklets/) <!-- TAGS: kernel,linux -->
- [Kernel Hacking for Hobbyists](http://events.linuxfoundation.org/sites/events/files/slides/linuxcon2-expanded.pdf) <!-- TAGS: kernel,linux -->
- [Systematic Testing of Fault Handling Code in Linux Kernel](https://events.static.linuxfound.org/sites/events/files/slides/20141015-LinuxCon-LFSV.pdf) <!-- TAGS: kernel,linux -->
- [Improving application responsiveness and I/O latency with the BFQ I/O scheduler](https://events.static.linuxfound.org/sites/events/files/slides/BFQ-LC14.pdf) <!-- TAGS: kernel,linux -->
- [Where should I start if I want to learn about the linux kernel? : linux](https://www.reddit.com/r/linux/comments/3z25xb/where_should_i_start_if_i_want_to_learn_about_the/) <!-- TAGS: kernel,linux -->
- [A Short Guide to Kernel Debugging - Square Corner Blog - Medium](https://medium.com/square-corner-blog/a-short-guide-to-kernel-debugging-e6fdbe7bfcdf) <!-- TAGS: blog,kernel,linux -->
- [Qemu and the Kernel » Linux Magazine](http://www.linux-magazine.com/Online/Features/Qemu-and-the-Kernel) <!-- TAGS: debug,kernel,linux -->
- [Introduction · Linux Inside](https://0xax.gitbooks.io/linux-insides/content/index.html) <!-- TAGS: book,documentation,kernel,linux -->
- [Queueing in the Linux Network Stack – Dan Siemon](https://www.coverfire.com/articles/queueing-in-the-linux-network-stack/) <!-- TAGS: kernel,linux,network -->
- [GitHub - mewmew/dissection: The dissection of a simple "hello world" ELF binary.](https://github.com/mewrev/dissection) <!-- TAGS: elf,linux -->
- [mauro-stettler: Monitoring a file to get details about write operations](http://mauro-stettler.blogspot.co.uk/2016/01/monitoring-a-file-to-get-details-about-write-operations.html?m=1) <!-- TAGS: linux,monitor -->
- [The 101 of ELF files on Linux: Understanding and Analysis - Linux Audit](https://linux-audit.com/elf-binaries-on-linux-understanding-and-analysis/) <!-- TAGS: blog,elf,linux -->
- [Getting involved with the Fedora kernel - Fedora Magazine](https://fedoramagazine.org/getting-involved-with-the-fedora-kernel/) <!-- TAGS: kernel,linux -->
- [New zine: Linux debugging tools you'll love - Julia Evans](https://jvns.ca/blog/2016/09/07/new-zine-linux-debugging-tools-youll-love/) <!-- TAGS: kernel,linux -->
- [The Linux Kernel documentation — The Linux Kernel documentation](https://www.kernel.org/doc/html/latest/index.html) <!-- TAGS: documentation,kernel,linux -->
- [Linux – IO Multiplexing – Select vs Poll vs Epoll – Developers Area](http://devarea.com/linux-io-multiplexing-select-vs-poll-vs-epoll/#.Wn1993XFLmF) <!-- TAGS: kernel,linux -->
- [500 Data Structures and Algorithms interview questions and their solutions - Techie Delight - Quora](https://techiedelight.quora.com/500-Data-Structures-and-Algorithms-practice-problems-and-their-solutions) <!-- TAGS: algorithm,blog,data structure,interview -->
- [HOW TO ANSWER: What Is Your Greatest Weakness?](https://biginterview.com/blog/2014/02/what-is-your-greatest-weakness.html) <!-- TAGS: interview -->
- [Untitled](http://infolab.stanford.edu/~ullman/focs/ch09.pdf) <!-- TAGS: algorithm,data structure,graph,interview -->
- [140 Google Interview Questions | Impact Interview](https://www.impactinterview.com/2009/10/140-google-interview-questions/) <!-- TAGS: interview -->
- [The Fascinating World of Linux System Calls | Sysdig](https://sysdig.com/blog/fascinating-world-linux-system-calls/) <!-- TAGS: interview,linux -->
- [Big-O Algorithm Complexity Cheat Sheet (Know Thy Complexities!) @ericdrowell](http://bigocheatsheet.com/) <!-- TAGS: algorithm,interview -->
- [SORTING](http://sorting.at/) <!-- TAGS: algorithm,interview -->
- [algorithm - Division without using '/' - Stack Overflow](https://stackoverflow.com/questions/5386377/division-without-using) <!-- TAGS: interview -->
- [What is better, adjacency lists or adjacency matrices for graph problems in C++? - Stack Overflow](https://stackoverflow.com/questions/2218322/what-is-better-adjacency-lists-or-adjacency-matrices-for-graph-problems-in-c) <!-- TAGS: c,graph,interview -->
- [Three ways to store a graph in memory, advantages and disadvantages - Stack Overflow](https://stackoverflow.com/questions/3287003/three-ways-to-store-a-graph-in-memory-advantages-and-disadvantages) <!-- TAGS: graph,interview -->
- [Algorithm of the Week: Graphs and Their Representation - DZone Database](https://dzone.com/articles/algorithm-week-graphs-and) <!-- TAGS: agile,algorithms,article,big data,cloud,database,devops,graph,graph databases,interview,iot,java,mobile,neo4j,nosql,programming,software development,web -->
- [algorithm - Comparing object graph representation to adjacency list and matrix representations - Stack Overflow](https://stackoverflow.com/questions/5886274/comparing-object-graph-representation-to-adjacency-list-and-matrix-representatio) <!-- TAGS: graph,interview -->
- [STL Algorithms in Action](https://hgad.net/posts/stl-algorithms-in-action/) <!-- TAGS: blog,cpp,documentation,interview,stl -->
- [Help! Help! There be dragons in the Kingdom o' many isles! The kingdom consis - Pastebin.com](https://pastebin.com/ip1jjmS6) <!-- TAGS: interview -->
- [If you had to ask 1 single C++ question to determine the level of a programmer, what would it be ? : cpp](https://www.reddit.com/r/cpp/comments/4l5nvx/if_you_had_to_ask_1_single_c_question_to/) <!-- TAGS: cpp,interview -->
- [The Quest For A Perfect C++ Interview Question - A CODER'S JOURNEY](http://www.acodersjourney.com/2016/06/the-quest-for-a-perfect-c-interview-question/) <!-- TAGS: cpp,interview -->
- [C++ Interview Questions and Answers for Freshers, Experienced - Page 4](http://a4academics.com/interview-questions/57-c-plus-plus/419-cpp-interview-questions-answers?showall=&start=3) <!-- TAGS: cpp,interview -->
- [Functions - C++ Programming Questions and Answers](http://www.indiabix.com/cpp-programming/functions/) <!-- TAGS: answers,cpp,download,ebooks,entrance,exam,examples,explanation,freshers,functions,general,interview,microbiology,online,pdf,questions,quiz,solutions,test -->
- [remote-jobs/README.md at master · remoteintech/remote-jobs · GitHub](https://github.com/remoteintech/remote-jobs/blob/master/README.md) <!-- TAGS: interview -->
- [Linear Algebra Refresher Course | Udacity](https://eu.udacity.com/course/linear-algebra-refresher-course--ud953) <!-- TAGS: course -->
- [High Performance Computing | Udacity](https://eu.udacity.com/course/high-performance-computing--ud281) <!-- TAGS: course -->
- [High Performance Computer Architecture | Udacity](https://eu.udacity.com/course/high-performance-computer-architecture--ud007) <!-- TAGS: course -->
- [Advanced Operating Systems | Udacity](https://eu.udacity.com/course/advanced-operating-systems--ud189) <!-- TAGS: course -->
- [Computer Science, M.Sc. | Part time online | Georgia Institute of Technology (Georgia Tech) | United States](https://www.mastersportal.eu/studies/101142/computer-science.html#content:contents) <!-- TAGS: master -->
- [FAQ | OMSCS | Georgia Institute of Technology | Atlanta, GA](https://www.omscs.gatech.edu/prospective-students/faq) <!-- TAGS: master -->
- [Clang - Getting Started](http://clang.llvm.org/get_started.html) <!-- TAGS: llvm -->
- [Checker Developer Manual](http://clang-analyzer.llvm.org/checker_dev_manual.html) <!-- TAGS: llvm -->
- [Understanding the Clang AST](https://jonasdevlieghere.com/understanding-the-clang-ast/) <!-- TAGS: ast,blog,clang,llvm -->
- [Clang & LLVM: How they can improve your life as a developer](https://events.static.linuxfound.org/sites/events/files/slides/linuxcon-europe-2014-llvm.pdf) <!-- TAGS: clang,cpp,llvm -->
- [C++ Static Analysis using Clang – Ehsan Akhgari](https://ehsanakhgari.org/blog/2015-12-07/c-static-analysis-using-clang) <!-- TAGS: blog,clang,cpp,llvm -->
- [How to write a checker in 24 hours](http://llvm.org/devmtg/2012-11/Zaks-Rose-Checker24Hours.pdf) <!-- TAGS: clang,cpp,llvm -->
- [Efficient Integer Overflow Checking in LLVM – Embedded in Academia](https://blog.regehr.org/archives/1384) <!-- TAGS: blog,llvm -->
- [LLVM-based Mutation Testing System. Request For Comments - Low Level Bits](https://lowlevelbits.org/llvm-based-mutation-testing-system.-request-for-comments/) <!-- TAGS: blog,clang,cpp,llvm,mutation testing,testing -->
- [FOSDEM 2018 - Introduction to LLVM](https://fosdem.org/2018/schedule/event/introduction/) <!-- TAGS: llvm -->
- [Adrian Sampson: LLVM for Grad Students](http://www.cs.cornell.edu/~asampson/blog/llvm.html) <!-- TAGS: llvm -->
- [3.8.1rc1 Documentation](https://docs.python.org/) <!-- TAGS: documentation,python -->
- [The Web framework for perfectionists with deadlines | Django](https://www.djangoproject.com/) <!-- TAGS: django,framework,open-source,python -->
- [Flask | The Pallets Projects](http://flask.pocoo.org/) <!-- TAGS: flask,python -->
- [Moving from Python 2 to Python 3](http://ptgmedia.pearsoncmg.com/imprint_downloads/informit/promotions/python/python2python3.pdf) <!-- TAGS: python -->
- [Getting Started with Haystack — Haystack 2.5.0 documentation](http://django-haystack.readthedocs.io/en/master/tutorial.html) <!-- TAGS: django,python -->
- [Quick start — Whoosh 2.7.4 documentation](http://whoosh.readthedocs.io/en/latest/quickstart.html) <!-- TAGS: python -->
- [Templating With Jinja2 in Flask: Essentials](https://code.tutsplus.com/tutorials/templating-with-jinja2-in-flask-essentials--cms-25571) <!-- TAGS: flask,jinja2,python -->
- [Ideas - O'Reilly Media](https://www.safaribooksonline.com/blog/2013/11/27/flask-internationalization-and-localization/) <!-- TAGS: flash,pybabel,python -->
- [How I wrote a self-hosting C compiler in 40 days](https://www.sigbus.info/how-i-wrote-a-self-hosting-c-compiler-in-40-days.html) <!-- TAGS: c,compiler -->
- [How to C (as of 2016)](https://matt.sh/howto-c) <!-- TAGS: blog,c,modern -->
- [language agnostic - Learning to write a compiler - Stack Overflow](https://stackoverflow.com/questions/1669/learning-to-write-a-compiler) <!-- TAGS: compiler -->
- [Baby Steps to a C Compiler – Wilfred Hughes::Blog](http://www.wilfred.me.uk/blog/2014/08/27/baby-steps-to-a-c-compiler/) <!-- TAGS: c,compiler -->
- [The Compiler Writer Resource Page](http://c9x.me/compile/bib/) <!-- TAGS: blog,compiler,documentation -->
- [Hotpatching a C Function on x86 « null program](http://nullprogram.com/blog/2016/03/31/) <!-- TAGS: asm,blog,c,x86 -->
- [Vim and Ctags - Andrew Stewart](https://andrew.stwrt.ca/posts/vim-ctags/) <!-- TAGS: ctags,vim -->
- [Vim Awesome](https://vimawesome.com/) <!-- TAGS: vim -->
- [Vim Refactoring Patterns · deliberate software](http://deliberate-software.com/vim-refactoring-patterns/) <!-- TAGS: dev,vim -->
- [Compiler Engineers Wanted! – Embecosm](http://www.embecosm.com/2017/01/11/compiler-engineers-wanted/) <!-- TAGS: compiler -->
- [The little book about OS development](http://littleosbook.github.io/) <!-- TAGS: book,os -->
- [6.828 / Fall 2017](https://pdos.csail.mit.edu/6.828/2017/xv6.html) <!-- TAGS: course,os -->
- [Why is there not a Master degree in Computer Operating Systems? : compsci](https://www.reddit.com/r/compsci/comments/1k0soo/why_is_there_not_a_master_degree_in_computer/) <!-- TAGS: os -->
- [www:getting-started:start [Wiki]](http://wiki.minix3.org/doku.php?id=www:getting-started:start) <!-- TAGS: getting-started,os,start,www -->
- [A Unikernel eBook from O'Reilly | Unikernels](http://unikernel.org/blog/2016/unikernel-ebook) <!-- TAGS: book,os -->
- [ops-class.org | Learn Operating Systems Online](https://www.ops-class.org/) <!-- TAGS: course,documentation,kernel,os -->
- [50 Linux Resources For Developers - inventropy](https://inventropy.us/blog/50-linux-resources-for-developers) <!-- TAGS: dev -->
- [Lecture Slides for Algorithm Design by Jon Kleinberg And Éva Tardos](http://www.cs.princeton.edu/~wayne/kleinberg-tardos/) <!-- TAGS: algorithm,course -->
- [Beginner's guide to IRC - Fedora Magazine](https://fedoramagazine.org/beginners-guide-irc/) <!-- TAGS: dev,irc -->
- [12 Most Influential Books Every Software Engineer Needs to Read – The Curious Programmer - Linkis.com](http://linkis.com/jasonroell.com/2015/MLBjj) <!-- TAGS: book,dev -->
- [GitHub - EbookFoundation/free-programming-books: Freely available programming books](https://github.com/EbookFoundation/free-programming-books) <!-- TAGS: book -->
- [Git tips from the trenches | Ochronus onLine | where the rising ape meets the falling angel](https://ochronus.com/git-tips-from-the-trenches/) <!-- TAGS: blog,dev,git,git branch,git diff,git howto,git tips,learn git,tip -->
- [19 Git Tips For Everyday Use](https://www.alexkras.com/19-git-tips-for-everyday-use/) <!-- TAGS: dev,git -->
- [Geektalk | Blog by Olve Maudal](https://olvemaudal.com/talks/) <!-- TAGS: dev -->
- [Tracking Down Heap Overflows with rr – Sean Heelan's Blog](https://sean.heelan.io/2016/05/31/tracking-down-heap-overflows-with-rr/) <!-- TAGS: debug,dev -->
- [Color Hunt - Trendy Color Palettes](http://colorhunt.co/c/28905) <!-- TAGS: color,dev -->
- [cube composer](https://david-peter.de/cube-composer/) <!-- TAGS: dev,game -->
- [The best Linux games: 35 killer PC games for Linux | PCWorld](https://www.pcworld.com/article/2363780/software-games/linux-gaming-rising-7-big-name-pc-games-that-now-call-linux-home.html) <!-- TAGS: game -->
- [HugeDomains.com - KfirlaVi.COM is for sale (Kfirla Vi)](http://www.kfirlavi.com/blog/2012/11/14/defensive-bash-programming/) <!-- TAGS: bash -->
- [explainshell.com - match command-line arguments to their help text](https://explainshell.com/) <!-- TAGS: bash -->
- [Inside ARM's Cortex-A72 microarchitecture - The Tech Report](https://techreport.com/review/28189/inside-arm-cortex-a72-microarchitecture) <!-- TAGS: arm,asm -->
- [Introduction to ARMv8 64-bit Architecture - UIC Academy](https://quequero.org/2014/04/introduction-to-arm-architecture/) <!-- TAGS: arm,asm,blog -->
- [Decoding Syscalls in ARM64 · ARM Ninja](http://arm.ninja/2016/03/07/decoding-syscalls-in-arm64/) <!-- TAGS: arm,asm,blog -->
- [Hack The Box :: Penetration Testing Labs](https://www.hackthebox.eu/) <!-- TAGS: hacking,pen testing,pen testing labs,penetration testing,penetration testing labs,penetration testing training -->
- [Kali Linux | Penetration Testing and Ethical Hacking Linux Distribution](https://www.kali.org/) <!-- TAGS: hacking -->
- [Infosec Training and Penetration Testing | Offensive Security](https://www.offensive-security.com/) <!-- TAGS: course,ethical hacking courses,hacking,information security training,infosec certifications,kali linux training,offensive security training,online security training,penetration testing services,pentest training,professional services -->
- [Metasploit | Penetration Testing Software, Pen Testing Security | Metasploit](https://www.metasploit.com/) <!-- TAGS: hacking -->
- [Getting started with Radare2](http://blog.dutchcoders.io/getting-started-with-radare2/) <!-- TAGS: blog,hacking,radare2,sec -->
- [WidePath | Next-Gen WordPress Hosting | Managed WordPress Hosting](https://bitrot.sh/) <!-- TAGS: blog,hacking -->
- [O RLY Parody Book Generator - DEV Community 👩‍💻👨‍💻](https://dev.to/rly) <!-- TAGS: book,engineering,javascript,joke,rails,ruby,software development -->
- [LMGTFY - Search Made Easy](http://lmgtfy.com/) <!-- TAGS: funny,joke,search -->
- [Documentation - The Go Programming Language](https://golang.org/doc/) <!-- TAGS: documentation,go -->
- [A Tour of Go](https://tour.golang.org/list) <!-- TAGS: documentation,go -->
- [5 advanced testing techniques in Go · Segment Blog](https://segment.com/blog/5-advanced-testing-techniques-in-go/) <!-- TAGS: blog,go -->
- [Learn Rust - Rust Programming Language](https://www.rust-lang.org/en-US/documentation.html) <!-- TAGS: documentation,rust -->
- [The Rust Programming Language - The Rust Programming Language](https://doc.rust-lang.org/book/) <!-- TAGS: book,rust -->
- [Secrets - Kubernetes](https://kubernetes.io/docs/concepts/configuration/secret/#use-case-dotfiles-in-secret-volume) <!-- TAGS: documentation,k8s -->
- [Ian's TechBlog: Dbus Tutorial - Fun with Network Manager](http://cheesehead-techblog.blogspot.co.uk/2012/09/dbus-tutorial-fun-with-network-manager.html) <!-- TAGS: dbus -->
- [Using pandoc to produce reveal.js slides · jgm/pandoc Wiki · GitHub](https://github.com/jgm/pandoc/wiki/Using-pandoc-to-produce-reveal.js-slides) <!-- TAGS: markdown,pandoc,presentation,revealjs,slide -->
- [GitHub - Wandmalfarbe/pandoc-latex-template: A pandoc LaTeX template to convert markdown files to PDF or LaTeX.](https://github.com/Wandmalfarbe/pandoc-latex-template) <!-- TAGS: markdown,pandoc,report -->
- [Introduction | C++ Education | Google Developers](https://developers.google.com/edu/c++/) <!-- TAGS: course,cpp,google -->
- [Google's Python Class | Python Education | Google Developers](https://developers.google.com/edu/python/) <!-- TAGS: course,google,python -->
- [Moving from Gnome Desktop to i3 window manager on Arch Linux](https://briancaffey.github.io/2017/10/17/moving-from-gnome-to-i3-on-arch-linux.html) <!-- TAGS: blog,i3 -->
- [Configure httpd(8) on OpenBSD — Roman Zolotarev](https://www.romanzolotarev.com/openbsd/webserver.html) <!-- TAGS: bsd,openbsd,server,web -->
- [Understanding Linux filesystems: ext4 and beyond | Opensource.com](https://opensource.com/article/18/4/ext4-filesystem) <!-- TAGS: ext4,fs,linux,os -->
- [KLEE](https://klee.github.io/) <!-- TAGS: cpp,docker,klee,llvm -->
- [The Internals of PostgreSQL : Chapter 5 Concurrency Control](http://www.interdb.jp/pg/pgsql05.html) <!-- TAGS: buffer,concurrency,design,fdw,internal,internals,mvcc,optimizer,pg,pitr,planner,point-in-time-recovery,postgresql,query,replication,sql,stremaing,vacuum,wal -->
- [libdill](http://libdill.org/) <!-- TAGS: c,concurrency,go,lib -->
- [Modern C++ features - lambdas](https://arne-mertz.de/2015/10/new-c-features-lambdas/) <!-- TAGS: blog,cpp,lambda -->
- [Some things you didn’t know about kubectl - Kubernetes](https://kubernetes.io/blog/2015/10/some-things-you-didnt-know-about-kubectl_28/) <!-- TAGS: blog,k8s,kubectl -->
- [Papers and Presentations](http://sean-parent.stlab.cc/papers-and-presentations/) <!-- TAGS: blog,cpp,paper,talk -->
- [Shellcode Injection - Dhaval Kapil](https://dhavalkapil.com/blogs/Shellcode-Injection/) <!-- TAGS: aslr,assembly,beginner,blog,crafting,demonstration,developer,dhaval,gatech,geek,github,hack,iit,injection,kapil,pianist,programmer,roorkee,sdslabs,sec,security,shell,shellcode,tutorial,vampire,vulnerability -->
- [Named tuple for C++ | Victor Laskin's Blog](http://vitiy.info/named-tuple-for-cplusplus/) <!-- TAGS: blog,cpp,tuple -->
- [Radare 0.10.0](http://radare.today/posts/radare-0-10-0/) <!-- TAGS: blog,gui,hack,radare2,sec -->
- [[llvm-dev] Proposal: virtual constant propagation](http://lists.llvm.org/pipermail/llvm-dev/2016-January/094600.html) <!-- TAGS: clang,cpp,email,llvm,virtual -->
- [New Concurrent Hash Maps for C++](http://preshing.com/20160201/new-concurrent-hash-maps-for-cpp/) <!-- TAGS: blog,concurrency,cpp -->
- [Untitled](http://www.googoolia.com/micro/lecture/arm_assembly.pdf) <!-- TAGS: arm,talk -->
- [Unpacking Tuples in C++14 – Andreas Herrmann](http://aherrmann.github.io/programming/2016/02/28/unpacking-tuples-in-cpp14/) <!-- TAGS: blog,cpp,tuple -->
- [The road for reflection: Tagging types](http://manu343726.github.io/2016/03/13/the-road-for-reflection-tagging-types.html<Paste>) <!-- TAGS: blog,cpp,reflection -->
- [Krister Walfridsson’s blog: Pointer casts in C](https://kristerw.blogspot.co.uk/2016/03/pointer-casts-in-c.html) <!-- TAGS: asm,blog,c -->
- [Hack Your C++ With LLVM | Hackaday](https://hackaday.com/2015/08/05/hack-your-c-with-llvm/) <!-- TAGS: blog,clang,cpp,llvm -->
- [Introduction · Practical Guide to Bare Metal C++](https://arobenko.gitbooks.io/bare_metal_cpp/content/index.html) <!-- TAGS: bare metal,blog,cpp,documentation -->
- [How to write a Bloom filter in C++ · Michael Schmatz](http://blog.michaelschmatz.com/2016/04/11/how-to-write-a-bloom-filter-cpp/) <!-- TAGS: blog,cpp -->
- [A cache miss is not a cache miss](http://larshagencpp.github.io/blog/2016/05/01/a-cache-miss-is-not-a-cache-miss) <!-- TAGS: blog,cache,cpp -->
- [Pointer Overflow Checking – Embedded in Academia](https://blog.regehr.org/archives/1395) <!-- TAGS: asm,blog,c,cache,cpp -->
- [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/) <!-- TAGS: blog,git -->
- [Understanding glibc malloc – sploitF-U-N](https://sploitfun.wordpress.com/2015/02/10/understanding-glibc-malloc/) <!-- TAGS: blog,glib,malloc -->
- [Untitled](http://0.30000000000000004.com/) <!-- TAGS: blog,floating point,math -->
- [How to allocate memory](http://geocar.sdf1.org/alloc.html) <!-- TAGS: alloc,blog,linux,malloc,memory -->
- [Page Redirection](http://www.ilikebigbits.com/blog/2016/8/28/designing-a-fast-hash-table) <!-- TAGS: blog,cpp,hash table -->
- [From Mordor, with love: What you need _not_ know about std::function - Part 2](http://templated-thoughts.blogspot.co.uk/2016/09/what-you-need-not-know-about.html) <!-- TAGS: blog,cpp,function -->
- [My resume in an Operating system](http://www.mathieupassenaud.fr/resume/) <!-- TAGS: blog,os,resume -->
- [Bartek's coding blog: Top 5 Beautiful C++ std Algorithms Examples](https://www.bfilipek.com/2014/12/top-5-beautiful-c-std-algorithms.html) <!-- TAGS: bartlomiej,bartlomiej filipek,blog,c++,code,coding,cpp,filipek,gamedev,glsl,graphics,native,opengl,programming,shaders,software development,stl,teaching,tutorials,vc++,visual c++,windows -->
- [The Null Pointer Constant nullptr - ModernesCpp.com](http://www.modernescpp.com/index.php/the-null-pointer-constant-nullptr) <!-- TAGS: blog,c,cpp,null -->
- [More About Variadic Templates - Simplify C++!](https://arne-mertz.de/2016/11/more-variadic-templates/) <!-- TAGS: blog,cpp,template,variadic -->
- [Writing a Tiny x86 Bootloader - Joe Bergeron](http://joebergeron.io/posts/post_two.html) <!-- TAGS: asm,blog,bootloader,kernel,os -->
- [I Wrote a Faster Sorting Algorithm | Probably Dance](https://probablydance.com/2016/12/27/i-wrote-a-faster-sorting-algorithm/) <!-- TAGS: algo,blog,cpp,faster,sort -->
- [Using libclang to Parse C++ (aka libclang 101) | Shahar Mike's Web Spot](https://shaharmike.com/cpp/libclang/) <!-- TAGS: blog,clang,cpp,llvm -->
- [Docker Internals -- Docker Saigon](http://docker-saigon.github.io/post/Docker-Internals/) <!-- TAGS: blog,docker,internals -->
- [Pure Functions - ModernesCpp.com](http://www.modernescpp.com/index.php/pure-functions) <!-- TAGS: blog,cpp,functional -->
- [Appcanary - Everything you need to know about HTTP security headers](https://blog.appcanary.com/2017/http-security-headers.html) <!-- TAGS: blog,headers,http,sec -->
- [Learn C Programming With 9 Excellent Free Open Source Books - OSS Blog](https://www.ossblog.org/learn-c-programming-with-9-excellent-open-source-books/) <!-- TAGS: blog,book,c -->
- [Linux eBPF Tracing Tools](http://www.brendangregg.com/ebpf.html) <!-- TAGS: bcc,blog,bpf,dtrace,ebpf,examples,linux,linux tracing,os,performance,tools -->
- [Getting Started with Taskwarrior - Fedora Magazine](https://fedoramagazine.org/getting-started-taskwarrior/) <!-- TAGS: blog,task warrior,todo -->
- [std::transform, a central algorithm - Fluent C++](http://www.fluentcpp.com/2017/02/13/transform-central-algorithm/) <!-- TAGS: algorithm,blog,cpp,transform -->
- [Bartek's coding blog: C++ 17 Features](https://www.bfilipek.com/2017/01/cpp17features.html) <!-- TAGS: bartlomiej,bartlomiej filipek,blog,c++,code,coding,cpp,filipek,gamedev,glsl,graphics,native,opengl,programming,shaders,software development,teaching,tutorials,vc++,visual c++,windows -->
- [Welcome diusrex.com - BlueHost.com](http://www.diusrex.com/2017/02/red-black-trees-introduction/) <!-- TAGS: affordable web hosting,blog,blogger,blogs,business web site,cgi perl php hosting,cheap web hosting,cpp,data structure,domain name,domain name registration,free domain names,front page hosting,internet advertising,internet marketing,marketing,php hosting,picture hosting,provider,rbtree,small business,web design,web hosting,web log,web logs,web site,web site builder,web site hosting,web space,weblog,weblogs,webmaster -->
- [Welcome diusrex.com - BlueHost.com](http://www.diusrex.com/2017/02/painless-red-black-tree-implementation-insertion/) <!-- TAGS: affordable web hosting,blog,blogger,blogs,business web site,cgi perl php hosting,cheap web hosting,cpp,data structure,domain name,domain name registration,free domain names,front page hosting,internet advertising,internet marketing,marketing,php hosting,picture hosting,provider,rbtree,small business,web design,web hosting,web log,web logs,web site,web site builder,web site hosting,web space,weblog,weblogs,webmaster -->
- [Lambda Overdose - Simplify C++!](https://arne-mertz.de/2017/02/lambda-overdose/) <!-- TAGS: blog,cpp,lambda -->
- [Representing Code · Crafting Interpreters](http://www.craftinginterpreters.com/representing-code.html) <!-- TAGS: blog,grammar,interpreters,parser -->
- [Parallel Algorithms of the Standard Template Library - ModernesCpp.com](http://www.modernescpp.com/index.php/parallel-algorithm-of-the-standard-template-library) <!-- TAGS: blog,cpp,parallel,stl -->
- [Atomic Smart Pointers - ModernesCpp.com](http://www.modernescpp.com/index.php/atomic-smart-pointers) <!-- TAGS: atomic,blog,cpp -->
- [Krister Walfridsson’s blog: Branch prediction](https://kristerw.blogspot.co.uk/2017/02/branch-prediction.html) <!-- TAGS: blog,branch prediction,c -->
- [Writing An Interpreter In Go | Thorsten Ball](https://interpreterbook.com/) <!-- TAGS: blog,book,compiler,ebook,epub,go,golang,how-to,interpreter,mobi,monkey,pdf,programming,programming language -->
- [How I ended up writing a new real-time kernel [Dmitry Frank]](https://dmitryfrank.com/articles/how_i_ended_up_writing_my_own_kernel) <!-- TAGS: blog,c,embedded,kernel,programming -->
- [Heaptrack v1.0.0 Release - KDAB](https://www.kdab.com/heaptrack-v1-0-0-release/) <!-- TAGS: blog,heap,linux,profiler -->
- [YouTube](https://www.youtube.com/watch?v=qXccKQ_tGC0) <!-- TAGS: category theory,compartir,gratuito,lambda,subida,teléfono con cámara,teléfono con vídeo,video,vídeo -->
- [Krister Walfridsson’s blog: The cost of conditional moves and branches](https://kristerw.blogspot.co.uk/2017/03/the-cost-of-conditional-moves-and.html) <!-- TAGS: blog,branch prediction,conditional move,cpp -->
- [ctop](https://ctop.sh/) <!-- TAGS: container,ctop,monitoring -->
- [YouTube](https://www.youtube.com/watch?v=KaBz45nZEZw) <!-- TAGS: category theory,compartir,gratuito,subida,teléfono con cámara,teléfono con vídeo,video,vídeo -->
- [LLVM Project Blog: Devirtualization in LLVM and Clang](http://blog.llvm.org/2017/03/devirtualization-in-llvm-and-clang.html) <!-- TAGS: blog,clang,cpp,llvm,virtual -->
- [Welcome diusrex.com - BlueHost.com](http://www.diusrex.com/2017/03/painless-red-black-tree-implementation-deletion/) <!-- TAGS: affordable web hosting,blog,blogger,blogs,business web site,cgi perl php hosting,cheap web hosting,cpp,data structure,domain name,domain name registration,free domain names,front page hosting,internet advertising,internet marketing,marketing,php hosting,picture hosting,provider,rbtree,small business,web design,web hosting,web log,web logs,web site,web site builder,web site hosting,web space,weblog,weblogs,webmaster -->
- [ftrace: trace your kernel functions! - Julia Evans](https://jvns.ca/blog/2017/03/19/getting-started-with-ftrace/) <!-- TAGS: blog,ftrace,kernel,linux -->
- [Writing a Linux Debugger Part 1: Setup](https://blog.tartanllama.xyz/writing-a-linux-debugger-setup/) <!-- TAGS: blog,debugger,linux -->
- [Structure and Interpretation of Computer Programs, 2e](http://sarabander.github.io/sicp/) <!-- TAGS: book,design,interpreter -->
- [Get started writing your own web services using Python Flask | Opensource.com](https://opensource.com/article/17/3/writing-web-service-using-python-flask) <!-- TAGS: aws,blog,flask,python -->
- [A journey into Radare 2 – Part 1: Simple crackme – Megabeets](https://www.megabeets.net/a-journey-into-radare-2-part-1/) <!-- TAGS: blog,radare2,sec -->
- [A FreeBSD 11 Desktop How-to » Cooltrainer.org](https://cooltrainer.org/a-freebsd-desktop-howto/) <!-- TAGS: blog,desktop,freebsd,gnome,guide,howto,tutorial -->
- [Writing Our Own Simple Memory Manager In C/C++ - CodeProject](https://www.codeproject.com/Articles/1180826/Writing-Our-Own-Simple-Memory-Manager-In-C-Cpluspl) <!-- TAGS: beginner,blog,c / c++ language,c++,c++builder,cpp,design,dev,devops,free source code,languages,linux,memory,memory manager,qa,sysadmin,tutorials -->
- [Haskell's Missing Concurrency Basics](https://www.snoyman.com/blog/2016/11/haskells-missing-concurrency-basics) <!-- TAGS: blog,concurrency,haskell -->
- [Clang-Tidy, part 1: Modernize your source code using C++11/C++14 - KDAB](https://www.kdab.com/clang-tidy-part-1-modernize-source-code-using-c11c14) <!-- TAGS: blog,clang,clang-tidy,cpp -->
- [Persistent Undo in Vim - Jovica Ilic](https://jovicailic.org/2017/04/vim-persistent-undo/) <!-- TAGS: blog,undo,vim -->
- [An Introduction to Reflection in C++](http://jackieokay.com/2017/04/13/reflection1.html) <!-- TAGS: blog,clang,cpp,llvm,reflection -->
- [gdb Debugging Full Example (Tutorial): ncurses](http://www.brendangregg.com/blog/2016-08-09/gdb-example-ncurses.html) <!-- TAGS: blog,debugger,debugging,gdb,gdb example,gdb tutorial -->
- [C++17- std::byte and std::filesystem - ModernesCpp.com](http://www.modernescpp.com/index.php/c-17-more-details-about-the-library) <!-- TAGS: blog,cpp,fs -->
- [Invert Binary Tree | Recursive and Iterative solution - Techie Delight](http://www.techiedelight.com/invert-binary-tree-recursive-iterative/) <!-- TAGS: algorithm,blog,cpp,data structure -->
- [YouTube](https://www.youtube.com/watch?v=jDPAtUfnoBU) <!-- TAGS: compartir,gratuito,llvm,subida,teléfono con cámara,teléfono con vídeo,video,vídeo -->
- [Rust container cheat sheet - Presentaciones de Google](https://docs.google.com/presentation/d/1q-c7UAyrUlM-eZyTo1pd8SZ0qwA_wYxmPZVOQkoDmH4/mobilepresent#slide=id.p) <!-- TAGS: container,documentation,rust -->
- [Linux Programming - Signals the easy way](https://www.stev.org/post/linuxprogrammingsignalstheeasyway) <!-- TAGS: #{keywords},blog,c,linux,signal -->
- [kernelCI: Linux Kernel Testing at kernelci.org - BayLibre](http://baylibre.com/intro-kernelci/) <!-- TAGS: blog,ci,kernel,linux,testing -->
- [Rust your ARM microcontroller! | Embedded in Rust](http://blog.japaric.io/quickstart/) <!-- TAGS: arm,blog,development,embedded,rust -->
- [Introduction to Template Meta Programming](http://www.aerialmantis.co.uk/blog/2017/05/01/introduction-to-template-meta-programming/) <!-- TAGS: blog,cpp,tmp -->
- [Test Doubles - Fakes, Mocks and Stubs. - DEV Community 👩‍💻👨‍💻](https://dev.to/milipski/test-doubles---fakes-mocks-and-stubs) <!-- TAGS: blog,community,engineering,inclusive,software development,tdd,testing -->
- [Introduction to Low Level Bit Hacks](http://www.catonmat.net/blog/low-level-bit-hacks-you-absolutely-must-know/) <!-- TAGS: bitwise,blog,tutorial -->
- [What is LLVM? The power behind Swift, Rust, Clang, and more | InfoWorld](https://www.infoworld.com/article/3247799/development-tools/what-is-llvm-the-power-behind-swift-rust-clang-and-more.amp.html) <!-- TAGS: blog,llvm -->
- [Functional programming for embedded systems - Sascha Grunert - Medium](https://medium.com/@saschagrunert/functional-programming-for-embedded-systems-4425ddd8435b) <!-- TAGS: blog,cpp,functional -->
- [My First Go Microservice using MongoDB and Docker Multi-Stage Builds](https://www.melvinvivas.com/my-first-go-microservice/) <!-- TAGS: blog,docker,go,microservice,mongodb -->
- [Functional Programmer Lingo in Verse · codemiller](http://www.codemiller.com/2014/08/01/functional-programmer-lingo-in-verse/) <!-- TAGS: blog,functional -->
- [GTmetrix | Website Speed and Performance Optimization](https://gtmetrix.com/) <!-- TAGS: performance,test,tool,website -->
- [How to start a Go project in 2018 | Ben E. C. Boyter](https://boyter.org/posts/how-to-start-go-project-2018/) <!-- TAGS: blog,go -->
- [Introduction · mostly-adequate-guide](https://mostly-adequate.gitbooks.io/mostly-adequate-guide/) <!-- TAGS: book,functional -->
- [Project Zero: Exploiting the Linux kernel via packet sockets](https://googleprojectzero.blogspot.co.uk/2017/05/exploiting-linux-kernel-via-packet.html) <!-- TAGS: blog,exploit,kernel -->
- [vittorio romeo's website](https://vittorioromeo.info/index/blog/variants_lambdas_part_3.html) <!-- TAGS: blog,cpp,lambda,variant -->
- [Fuzzing Irssi](https://irssi.org/2017/05/12/fuzzing-irssi/) <!-- TAGS: blog,fuzzing,irssi,testing -->
- [Learn CMake's Scripting Language in 15 Minutes](http://preshing.com/20170522/learn-cmakes-scripting-language-in-15-minutes/) <!-- TAGS: blog,cmake -->
- [Understanding Virtual Tables In C++](http://ariasalpablo.blogspot.co.uk/2017/05/understanding-virtual-tables-in-c.html) <!-- TAGS: blog,cpp,vtable -->
- [Linux Shellcoding (Part 1.0) - Exploit Development - 0x00sec - The Home of the Hacker](https://0x00sec.org/t/linux-shellcoding-part-1-0/289) <!-- TAGS: blog,linux,shellcode -->
- [Async IO on Linux: select, poll, and epoll - Julia Evans](https://jvns.ca/blog/2017/06/03/async-io-on-linux--select--poll--and-epoll/) <!-- TAGS: blog,c,syscall -->
- [Linux Bridge - how it works](https://goyalankit.com/blog/linux-bridge) <!-- TAGS: blog,bridge,linux,network -->
- [SUE 2017 - Radare Project - Sergi 'pancake' Alvarez on Vimeo](https://vimeo.com/211371081) <!-- TAGS: arm,asm,radare2,video -->
- [Haskell for all: Translating a C++ parser to Haskell](http://www.haskellforall.com/2017/06/translating-c-parser-to-haskell.html) <!-- TAGS: blog,cpp,haskell -->
- [RE guide for beginners: Methodology and tools - Reverse Engineering - 0x00sec - The Home of the Hacker](https://0x00sec.org/t/re-guide-for-beginners-methodology-and-tools/2242) <!-- TAGS: blog,reverse engineering,tool -->
- [Algorithms Behind Modern Storage Systems - ACM Queue](https://queue.acm.org/detail.cfm?id=3220266) <!-- TAGS: algorithm,blog,data structure,storage -->
- [std::accumulate vs. std::reduce](https://blog.tartanllama.xyz/accumulate-vs-reduce/) <!-- TAGS: blog,cpp,parallel,stl -->
- [Bartek's coding blog: The Pimpl Pattern - what you should know](https://www.bfilipek.com/2018/01/pimpl.html) <!-- TAGS: bartlomiej,bartlomiej filipek,blog,c++,code,coding,cpp,design,filipek,gamedev,glsl,graphics,native,opengl,pimpl,programming,shaders,software development,teaching,tutorials,vc++,visual c++,windows -->
- [Debugging the Linux Kernel – Own your bits](https://ownyourbits.com/2018/05/09/debugging-the-linux-kernel/) <!-- TAGS: blog,debugging,kernel -->
- [The Kernel Newbie Corner: Kernel and Module Debugging with gdb - Linux.com](https://www.linux.com/learn/kernel-newbie-corner-kernel-and-module-debugging-gdb) <!-- TAGS: blog,debugging,kernel -->
- [MIR borrowck - Guide to Rustc Development](https://rust-lang-nursery.github.io/rustc-guide/mir-borrowck.html) <!-- TAGS: borrow,documentation,rust -->
- [Bartek's coding blog: pimpl vs Abstract Interface - a practical tutorial](https://www.bfilipek.com/2018/01/pimpl-interface.html) <!-- TAGS: abstract,bartlomiej,bartlomiej filipek,blog,c++,code,coding,cpp,filipek,gamedev,glsl,graphics,interface,native,opengl,pimpl,programming,shaders,software development,teaching,tutorials,vc++,visual c++,windows -->
- [The musings of bluz71](https://bluz71.github.io/2017/05/21/vim-plugins-i-like.html) <!-- TAGS: blog,plugin,vim -->
- [Introduction · Radare2 Explorations](https://monosource.gitbooks.io/radare2-explorations/content/) <!-- TAGS: book,radare2 -->
- [Vim - Full Stack Python](https://www.fullstackpython.com/vim.html) <!-- TAGS: blog,python,vim -->
- [https://zachgrace.com/cheat_sheets/radare2/](https://zachgrace.com/cheat_sheets/radare2.html) <!-- TAGS: blog,cheat sheet,radare2 -->
- [How to Clang Your Dragon 🐉 | Skilled.io, the Swift Community.](https://www.skilled.io/u/playgroundscon/building-a-compiler) <!-- TAGS: blog,clang,compiler,llvm -->
- [Continuous Integration for C/C++ Projects with Jenkins and Conan](https://jenkins.io/blog/2017/07/07/jenkins-conan) <!-- TAGS: blog,conan,cpp,jenkins -->
- [Google CTF 2017 – Pwnables – Inst_Prof – Writeup – dabooze](https://dilsec.com/2017/07/06/google-ctf-2017-pwnables-inst_prof-writeup/) <!-- TAGS: blog,radare2,sec,writeup -->
- [RustBelt: Securing the Foundations of the Rust Programming Language](https://www.ralfj.de/blog/2017/07/08/rustbelt.html) <!-- TAGS: blog,rust -->
- [Upgrading shells to fully interactive TTYs](https://blog.ropnop.com/upgrading-simple-shells-to-fully-interactive-ttys/) <!-- TAGS: blog,exploit,tty -->
- [OpenBSD on the Huawei MateBook X | joshua stein](https://jcs.org/2017/07/14/matebook) <!-- TAGS: blog,install,openbsd,tutorial -->
- [Writing ARM Shellcode | Azeria Labs](https://azeria-labs.com/writing-arm-shellcode/) <!-- TAGS: arm,asm,blog,shellcode -->
- [Steganography in contemporary cyberattacks | Securelist](https://securelist.com/steganography-in-contemporary-cyberattacks/79276/) <!-- TAGS: analysis,apt,blog,global research and analysis team,great,kaspersky,malware statistics,phishing,sec,security,spam,steg,steganography,virus statistics -->
- [Nicole Orchard](https://nicoleorchard.com/blog/compilers) <!-- TAGS: blog,compiler,llvm -->
- [Top 20 C++ multithreading mistakes and how to avoid them - A CODER'S JOURNEY](http://www.acodersjourney.com/2017/08/top-20-cplusplus-multithreading-mistakes/) <!-- TAGS: blog,cpp,multithreading,thread -->
- [Why Go is my favorite programming language](https://michael.stapelberg.de/posts/2017-08-19-golang_favorite/) <!-- TAGS: blog,debian,go,linux,michael,stapelberg -->
- [Bartek's coding blog: Micro benchmarking libraries for C++](https://www.bfilipek.com/2016/01/micro-benchmarking-libraries-for-c.html) <!-- TAGS: bartlomiej,bartlomiej filipek,benchmarking,blog,c++,code,coding,cpp,filipek,gamedev,glsl,graphics,native,opengl,programming,shaders,software development,teaching,tutorials,vc++,visual c++,windows -->
- [Building a RESTful API with Go](https://dev.to/codehakase/building-a-restful-api-with-go) <!-- TAGS: api,blog,go,restful -->
- [Unprivileged · IT Security Catalog](https://www.it-sec-catalog.info/analysis_and_exploitation_unprivileged.html) <!-- TAGS: blog,exploit,sec -->
- [How To Set Up PF Firewall on FreeBSD to Protect a Web Server - nixCraft](https://www.cyberciti.biz/faq/how-to-set-up-a-firewall-with-pf-on-freebsd-to-protect-a-web-server/) <!-- TAGS: blog,bsd,firewall,freebsd,openbsd,pf -->
- [5 Tips for Writing Small CLI Tools in Rust - Pascal’s Scribbles](https://deterministic.space/rust-cli-tips.html) <!-- TAGS: blog,cli,rust,tool -->
- [Clean http handlers in Go | Bart's programming blog](https://blog.bartfokker.nl/posts/clean-handlers/) <!-- TAGS: blog,go,http -->
- [How Does a Database Work? | Let’s Build a Simple Database](https://cstack.github.io/db_tutorial/) <!-- TAGS: blog,c,sqlite -->
- [Learning C++](https://blog.tartanllama.xyz/learning-cpp/) <!-- TAGS: blog,cpp,learning -->
- [Krister Walfridsson’s blog: Useful GCC warning options not enabled by -Wall -Wextra](https://kristerw.blogspot.co.uk/2017/09/useful-gcc-warning-options-not-enabled.html) <!-- TAGS: blog,gcc,warning -->
- [SensePost | Linux heap exploitation intro series: the magicians cape – 1 byte overflow](https://sensepost.com/blog/2017/linux-heap-exploitation-intro-series-the-magicians-cape-1-byte-overflow/) <!-- TAGS: blog,c,exploit,heap -->
- [pwnable.tw](https://pwnable.tw/) <!-- TAGS: hacking -->
- [Pipeline Patterns in Go - Statuscode - Medium](https://medium.com/statuscode/pipeline-patterns-in-go-a37bb3a7e61d) <!-- TAGS: blog,go,pattern,pipeline -->
- [Modern B-Tree Techniques](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.219.7269&rep=rep1&type=pdf) <!-- TAGS: book,btree,data structure,documentation -->
- [OverTheWire: Wargames](http://overthewire.org/wargames/) <!-- TAGS: hacking,wargame -->
- [Injecting a Running Process (Linux) — PoC || GTFO](https://www.real0day.com/hacking-tutorials/2017/11/6/injecting-a-running-process-linux) <!-- TAGS: blog,exploit,hacking,linux,sec -->
- [Assembly Basics Cheatsheet | Azeria Labs](https://azeria-labs.com/assembly-basics-cheatsheet/) <!-- TAGS: arm,asm,cheat sheet,exploit,sec -->
- [Part 3: Stack Overflow Challenges | Azeria Labs](https://azeria-labs.com/part-3-stack-overflow-challenges/) <!-- TAGS: arm,asm,blog,exploit,sec -->
- [Heap Exploitation - Fastbin Attack - Exploit Development - 0x00sec - The Home of the Hacker](https://0x00sec.org/t/heap-exploitation-fastbin-attack/3627) <!-- TAGS: blog,exploit,heap,sec -->
- [10 open-source Kubernetes tools for highly effective SRE and Ops Teams](https://abhishek-tiwari.com/10-open-source-tools-for-highly-effective-kubernetes-sre-and-ops-teams/) <!-- TAGS: blog,k8s,tool -->
- [50 Shades of Go: Traps, Gotchas, and Common Mistakes for New Golang Devs](http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/) <!-- TAGS: blog,go -->
- [Reversing ARM Binaries](https://zygosec.com/post1.html) <!-- TAGS: arm,asm,blog,reverse,sec -->
- [http2 explained - The HTTP/2 book](https://daniel.haxx.se/http2/) <!-- TAGS: blog,book,http2 -->
- [Linux Internals - The Art Of Symbol Resolution - Linux - 0x00sec - The Home of the Hacker](https://0x00sec.org/t/linux-internals-the-art-of-symbol-resolution/1488) <!-- TAGS: asm,blog,linux -->
- [Closures 101 | mttyng](http://mttyng.com/closures-101/) <!-- TAGS: blog,functional,rust -->
- [An introduction to LLVM in Go](https://felixangell.com/blog/an-introduction-to-llvm-in-go) <!-- TAGS: blog,go,llvm -->
- [/posts/how-to-read-write-llvm-bitcode/](http://www.duskborn.com/how-to-read-write-llvm-bitcode/) <!-- TAGS: blog,llvm -->
- [Embedded Rust: Why ?](https://ithinuel.me/embedded-rust-why/) <!-- TAGS: blog,embedded,rust -->
- [My experiences learning Rust – Page Fault Blog](https://pagefault.blog/2017/09/14/my-experiences-learning-rust/) <!-- TAGS: blog,rust -->
- [How to Pass a Polymorphic Object to an STL Algorithm - Fluent C++](https://www.fluentcpp.com/2018/04/17/pass-polymorphic-object-stl-algorithm/) <!-- TAGS: blog,cpp,polymorphism,stl -->
- [Bartek's coding blog: Refactoring with C++17 std::optional](https://www.bfilipek.com/2018/04/refactoring-with-c17-stdoptional.html) <!-- TAGS: bartlomiej,bartlomiej filipek,blog,c++,code,coding,cpp,filipek,gamedev,glsl,graphics,native,opengl,optional,programming,shaders,software development,teaching,tutorials,vc++,visual c++,windows -->
- [Asynchronous Processing with Go using Kafka and MongoDB](https://www.melvinvivas.com/developing-microservices-using-kafka-and-mongodb/) <!-- TAGS: async,blog,go,kafka,mongodb -->
- [Tearing apart printf() – MaiZure's Projects](http://www.maizure.org/projects/printf/index.html) <!-- TAGS: blog,c,syscall -->
- [ARM 32-Bit Assembly Basics Cheat Sheet (18" x 24")](https://gumroad.com/l/arm-assembly-cheat-sheet) <!-- TAGS: arm,asm,cheat sheet -->
- [C++ Core Guidelines: More Traps in the Concurrency - ModernesCpp.com](http://www.modernescpp.com/index.php/c-core-guidelines-the-remaining-rules-to-concurrency) <!-- TAGS: blog,concurrency,cpp -->
- [Tcpdump Examples - 22 Tactical Commands | HackerTarget.com](https://hackertarget.com/tcpdump-examples/) <!-- TAGS: blog,network,tcp,tcpdump -->
- [Go vs C++ : golang](https://www.reddit.com/r/golang/comments/8mp8oe/go_vs_c/) <!-- TAGS: blog,comparison,cpp,go -->
- [How the Go runtime implements maps efficiently (without generics) | Dave Cheney](https://dave.cheney.net/2018/05/29/how-the-go-runtime-implements-maps-efficiently-without-generics) <!-- TAGS: blog,go,map -->
- [A cartoon intro to DNS over HTTPS - Mozilla Hacks - the Web developer blog](https://hacks.mozilla.org/2018/05/a-cartoon-intro-to-dns-over-https/) <!-- TAGS: blog,dns,https,tutorial -->
- [PMU counters and profiling basics. | Easyperf](https://dendibakh.github.io/blog/2018/06/01/PMU-counters-and-profiling-basics) <!-- TAGS: blog,profiling -->
- [Tricking the HashMap | Ivan Dubrov](https://idubrov.github.io/rust/2018/06/01/tricking-the-hashmap.html) <!-- TAGS: blog,hashmap,map,rust,string -->
- [tail -f /var/log/messages | grep vegard: Compiler fuzzing, part 1](http://www.vegardno.net/2018/06/compiler-fuzzing.html) <!-- TAGS: blog,cpp,fuzzing -->
- [Krister Walfridsson’s blog: Useful GCC address sanitizer checks not enabled by default](https://kristerw.blogspot.com/2018/06/useful-gcc-address-sanitizer-checks-not.html) <!-- TAGS: blog,cpp,gcc,sanitizers -->
- [Carbon](https://carbon.now.sh) <!-- TAGS: code,create,image,tool -->
- [A Tutorial Introduction to Kubernetes](http://okigiveup.net/a-tutorial-introduction-to-kubernetes/) <!-- TAGS: blog,k8s,tutorial -->
- [Go compiler: SSA optimization rules description language · Iskander Sharipov technical blog](https://quasilyte.github.io/blog/post/go_ssa_rules/) <!-- TAGS: blog,compiler,go,ssa -->
- [Crafting Interpreters](http://craftinginterpreters.com/) <!-- TAGS: book,compiler,interpreter,tutorial -->
- [Google - Site Reliability Engineering](https://landing.google.com/sre/resources.html) <!-- TAGS: book,resources,sre -->
- [UNIX Syscalls](https://john-millikin.com/unix-syscalls) <!-- TAGS: blog,syscall,unix -->
- [CLI: improved](https://remysharp.com/2018/08/23/cli-improved) <!-- TAGS: blog,cli,commands,linux -->
- [bpftrace (DTrace 2.0) for Linux 2018](http://www.brendangregg.com/blog/2018-10-08/dtrace-for-linux-2018.html) <!-- TAGS: blog,bpf,bpftrace,dtrace,ebpf,linux,performance,tracing -->
- [Untitled](https://blog.k3170makan.com/2018/10/introduction-to-elf-format-part-i.html) <!-- TAGS: elf,executable,format,linux -->
- [Understanding… by Vladimir Likic, PhD [Leanpub PDF/iPad/Kindle]](https://leanpub.com/linuxkernel) <!-- TAGS: book,kernel,linux -->
- [Everything PKI - smallstep](https://smallstep.com/blog/everything-pki.html) <!-- TAGS: documentation,pki,tutorial -->
- [Handshake](https://www.handshake.org/) <!-- TAGS: ca,certificates,decentralized -->
- [Bullet Journal](https://bulletjournal.com/) <!-- TAGS: bulletjournal,note,process,style -->
- [Debugging Rust with VSCode on FreeBSD](http://venshare.com/debugging-rust-with-vscode-on-freebsd/amp/) <!-- TAGS: debugging,freebsd,rust,vscode -->
- [Playful Programming: How to speak at a conference](https://playfulprogramming.blogspot.com/2018/11/how-to-speak-at-conference.html) <!-- TAGS: conference,speaking -->
- [pwnable.xyz](https://pwnable.xyz/) <!-- TAGS: ctf -->
- [Santa's ELFs: Running Linux Executables Without execve](https://blog.rapid7.com/2019/01/03/santas-elfs-running-linux-executables-without-execve/) <!-- TAGS: elf,executable -->
- [Glibc Heap Exploitation Basics : Introduction to ptmalloc2 internals (Part 1)](https://blog.k3170makan.com/2018/11/glibc-heap-exploitation-basics.html) <!-- TAGS: glic,hacking,heap,security -->
- [The Process of Mastering a Skill | Azeria Labs](https://azeria-labs.com/the-process-of-mastering-a-skill/) <!-- TAGS: learning,master,process,skill -->
- [Introduction to Paging | Writing an OS in Rust](https://os.phil-opp.com/paging-introduction/) <!-- TAGS: os,pagination,rust -->
- [Data Breaches](https://www.databreaches.live/) <!-- TAGS: engine,hacking,se,search -->
- [Find people behind an email](https://pipl.com/) <!-- TAGS: engine,hacking,se,search -->
- [Home](https://censys.io/) <!-- TAGS: engine,hacking,se,search -->
- [Shodan](https://www.shodan.io/) <!-- TAGS: engine,hacking,se,search -->
- [GreyNoise Visualizer](https://viz.greynoise.io) <!-- TAGS: engine,hacking,se,search -->
- [ZoomEye - Cyberspace Search Engine](https://www.zoomeye.org/) <!-- TAGS: engine,hacking,se,search -->
- [网络空间安全搜索引擎，网络空间搜索引擎，网络空间测绘，安全态势感知 - FOFA网络空间测绘系统](https://fofa.so/) <!-- TAGS: engine,hacking,se,search,全网搜索,安全大数据,工控安全,态势感知,搜索引擎,漏洞分析,空间测绘,端口扫描,网络安全,网络空间 -->
- [ONYPHE - Your Internet SIEM](https://www.onyphe.io/) <!-- TAGS: api,connected objects,cti,engine,exposure assessment,geolocation,hacking,internet exposure,internet exposure assessment,internet of things,iot,ip data,ip geolocation,ip location,open source intelligence,open-source intelligence,osint,passive dns,passivedns,saas,se,search,siem,software as a service,software-as-a-service,threat data,threat intel,threat intelligence,threatdata,threatintel,threatintelligence -->
- [BinaryEdge Portal](https://app.binaryedge.io/) <!-- TAGS: engine,hacking,se,search -->
- [Find email addresses in seconds • Hunter (Email Hunter)](https://hunter.io) <!-- TAGS: engine,hacking,se,search -->
- [WiGLE: Wireless Network Mapping](https://wigle.net/) <!-- TAGS: 802.11,802.11b,dstumbler,engine,hacking,kismet,mapping,maps,net hugger,net hugging,netstumbler,se,search,war driving,wardriving,wifi,wireless,wireless mapping,wireless maps,wireless networks -->
- [Untitled](https://ghostproject.fr/) <!-- TAGS: engine,hacking,se,search -->
- [Getting Started - Asynchronous Programming in Rust](https://rust-lang.github.io/async-book/) <!-- TAGS: async,book,rust -->
- [CSS Reference - A free visual guide to CSS](https://cssreference.io/) <!-- TAGS: css,documentation,reference -->
- [Linux Reverse Engineering CTFs for Beginners | 🔐Blog of Osanda](https://osandamalith.com/2019/02/11/linux-reverse-engineering-ctfs-for-beginners/) <!-- TAGS: ctf,linux,reverse engineering -->
- [The Ultimate Guide To Memorable Tech Talks - Nina Zakharenko - Medium](https://medium.com/@nnja/the-ultimate-guide-to-memorable-tech-talks-e7c350778d4b) <!-- TAGS: conference,guide,specking,talk -->
- [GitHub - swisskyrepo/PayloadsAllTheThings: A list of useful payloads and bypass for Web Application Security and Pentest/CTF](https://github.com/swisskyrepo/PayloadsAllTheThings) <!-- TAGS: hacking,payload,security -->
- [Inserting records into a PostgreSQL database with Go's database/sql package - Calhoun.io](https://www.calhoun.io/inserting-records-into-a-postgresql-database-with-gos-database-sql-package/) <!-- TAGS: go,postgresql,sql,tutorial -->
- [Reading a Postgres EXPLAIN ANALYZE Query Plan](https://thoughtbot.com/blog/reading-an-explain-analyze-query-plan) <!-- TAGS: benchmark,postgresql,sql,tutorial -->
- [The One On Dynamic Programming!](https://blogarithms.github.io/articles/2019-03/cracking-dp-part-one) <!-- TAGS: blog,dynamic,programming,tutorial -->
- [Templating tmux with tmuxinator](https://thoughtbot.com/blog/templating-tmux-with-tmuxinator) <!-- TAGS: template,tmux -->
- [Concurrency with Python: Threads and Locks > Ying Wang](https://bytes.yingw787.com/posts/2019/01/12/concurrency_with_python_threads_and_locks/) <!-- TAGS: python,thread -->
- [Things you're probably not using in Python 3 - but should - Data, what now? turns](https://datawhatnow.com/things-you-are-probably-not-using-in-python-3-but-should/) <!-- TAGS: 3,blog,py3,python -->
- [K3s: Lightweight Kubernetes](https://k3s.io/) <!-- TAGS: k8s,small -->
- [The Kubernetes Operating System](https://k3os.io/) <!-- TAGS: k8s,os -->
- [A visual guide to Go Memory Allocator from scratch (Golang) | Ankur Anand](https://blog.ankuranand.com/2019/02/20/a-visual-guide-to-golang-memory-allocator-from-ground-up/) <!-- TAGS: blog,go,golang,internals,memory -->
- [From design patterns to category theory](https://blog.ploeh.dk/2017/10/04/from-design-patterns-to-category-theory/) <!-- TAGS: blog,category theory,dessign patters -->
- [Andreas Kling – I like computers!](https://awesomekling.github.io/) <!-- TAGS: blog,c++,cpp -->
- [Blog - Christine Dodrill](https://christine.website/blog) <!-- TAGS: blog,dessign,interesting -->
- [Linux, Netlink, and Go - Part 1: netlink · Matt Layher](https://mdlayher.com/blog/linux-netlink-and-go-part-1-netlink/) <!-- TAGS: blog,go,linux,netlink -->
- [Coroutines: A Million Stacks - Jaeger's Blog](http://www.mikemarcin.com/post/coroutine_a_million_stacks/) <!-- TAGS: blog,c++,coroutine,cpp -->
- [GitHub - hellerve/programming-talks: Awesome & interesting talks about programming](https://github.com/hellerve/programming-talks) <!-- TAGS: engineering,programming,software,talk,talks -->
- [Use plaintext email](https://useplaintext.email/) <!-- TAGS: client,email,html,plain text,simple -->
- [Comparisons in C++20](https://brevzin.github.io/c++/2019/07/28/comparisons-cpp20/) <!-- TAGS: blog,c++,comparison,cpp,operator,space ship -->
- [Monads as a Programming Pattern](https://samgrayson.me/2019-08-06-monads-as-a-programming-pattern/) <!-- TAGS: blog,category theory,category theoryblog,monads -->
- [Paged Out!](https://pagedout.institute/) <!-- TAGS: hacking,magazine -->
- [GitHub - lizhuohua/linux-kernel-module-rust](https://github.com/lizhuohua/linux-kernel-module-rust) <!-- TAGS: kernel,linux,module,rust -->
- [How to Build Good Software](https://www.csc.gov.sg/articles/how-to-build-good-software) <!-- TAGS: blog,design patterns,good software -->
- [4 Rules for Intuitive UX – Learn UI Design](https://learnui.design/blog/4-rules-intuitive-ux.html) <!-- TAGS: blog,dessign patterns,ux -->
- [Regex Crossword](https://regexcrossword.com/) <!-- TAGS: game,regex,regular expression -->
- [The Twelve-Factor App](https://12factor.net/) <!-- TAGS: app,blog,dessign -->
- [Martin Heinz - Personal Website & Blog](https://martinheinz.dev/blog/13) <!-- TAGS: blog,performance,python -->
- [On the shoulders of the giants](https://www.lpalmieri.com/posts/2020-03-08-on-the-shoulders-of-the-giants/) <!-- TAGS: blog,books -->
